config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  
  resources :articles

  
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  
  get 'signup', to: 'users#new'
  resources :users, except:[:new]

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum: 10}
    validates :description, presence: true, length: {minimum: 3, maximum: 3000}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    before_save { self.email = email.downcase }
    validates :username, 
              presence: true, 
              uniqueness: {case_sensitive: false}, 
              length: {minimum: 3, maximum: 20}
              
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
              uniqueness: {case_sensitive: false}, 
              length: {minimum: 3, maximum: 100},
              format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    
   def index
       @articles = Article.all
   end
   
   def new
      @article = Article.new
   end
   
   def edit
   end
   
   def create
      @article = Article.new(article_params)
      @article.user = User.first
      if @article.save
        flash[:success] = "Article Saved!"
        redirect_to article_path(@article)
      else
          render 'new'
      end
   end
   
   def update
      if @article.update(article_params)
        flash[:success] = "Article Updated!"
        redirect_to article_path(@article)
      else
          render 'edit'
      end
   end
   
   def show  
   end
   
   def destroy
       @article.destroy
       flash[:danger] = "Article deleted"
       redirect_to articles_path
   end
   
   private
   def set_article
      @article = Article.find(params[:id])
   end
   def article_params
      params.require(:article).permit(:title, :description)
   end
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
   def home
       
   end
   
   def about
       
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Nice!!! You have signed up the user #{@user.username}"
            redirect_to articles_path
        else
          render 'new'
        end
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="container">
    <%= render 'shared/errors', obj: @article %>
    <div class="row">
        <div class="col-xs-12">
            <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-6">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-10">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Article", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">
    <h1 align="center">All Posts</h1>

    <% @articles.each do |article| %>
    <article class="article">
        <div class="panel panel-info">
            <div class="panel-heading text-center">
                <strong><%= article.title %></strong>
            </div>
            <div class="panel-body">
                <%= article.description %>
            </div>
            <div class="panel-footer">
                <span><%= link_to "Show", article, class: "btn btn-md btn-info" %></span>
                <span><%= link_to "Edit", edit_article_path(article) , class: "btn btn-md btn-primary" %></span>
                <span><%= link_to "Remove", article, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-md btn-danger" %></span>
                <% if article.user %>
                    <div class="article-creator">
                        <small>
                            <p>created by <%= article.user.username %> <%=time_ago_in_words(article.created_at)%> ago</p>
                            <p>last updated <%= time_ago_in_words(article.created_at) %> ago</p>
                        </small>
                    </div>
                <% end %>
            </div>
        </div>
    </article>
        <br/>
    <% end %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create your article here</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div align="center">
    <h2><%= @article.title %></h2>
</div>

<div class="container">
    <div class="row">
        <div class="well col-xs-8 col-xs-offset-2">
            Description: <%= @article.description %>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-4 col-xs-offset-5">
            <span><%= link_to "Edit", edit_article_path(@article), class: "btn btn-md btn-primary" %></span>
            <span><%= link_to "Remove", @article, class: "btn btn-md btn-danger", method: :delete, data: { confirm: "Are you sure?" } %></span>
        </div>    
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Copyright © <a href="enter in a link here">The Complete Ruby on Rails Developer</a>
        by <a href="enter in a link here">Mashrur Hossain</a>
    </small>
    <nav>
        <ul>
        <li><%= link_to "About", about_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <%= link_to 'ALPHA BLOG', root_path, class: "navbar-brand", id: "logo" %>
    <ul class="nav navbar-nav">
      <li><%=link_to 'ABOUT', about_path%></li>
      <li><%=link_to 'ARTICLES', articles_path%></li>
      <li><%=link_to 'NEW POST', new_article_path%></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-primary" %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BOOM BLOG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<%= render 'layouts/messages' %>

<%= yield %>

<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/pages/about.html.erb
<h1>THIS IS THE ABOUT PAGE</h1>

app/views/pages/home.html.erb
<div class="jumbotron custom-jumbo">
  <div class="container">
    <div class="row">
      <div class ="col-xs-6">
        <div class="welcome-text">
          <h1>Chelsea</h1> <span class="block-text" id="home-page">Blog</span> <h1>Life</h1>
          <p>Welcome to my world</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, 'error') %>
                        prevented article from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/new.html.erb
<h1 align="center">Sign Up New User</h1>
<div class="container">
    <%= render 'shared/errors', obj: @user %>
    <div class="row">
        <div class="col-sm-offset-2 col-xs-12">
            <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :username %>
                </div>
                <div class="col-sm-4">
                <%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email %>
                </div>
                <div class="col-sm-4">
                <%= f.email_field :email, class: "form-control", placeholder: "Enter Email", autofocus: true %>
                </div>
            </div>
            
             <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :password %>
                </div>
                <div class="col-sm-4">
                <%= f.password_field :password, class: "form-control", placeholder: "Enter Password", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>